config/routes.rb
Rails.application.routes.draw do
  resources :puppet_modules
  resources :debuggers
  resources :puppet_versions
  resources :ruby_versions
  devise_for :users
  root to: "dashboard#index"
  resources :profiles

  resources :user_debugger_assignments, only: [:create, :destroy]
end

app/models/puppet_version.rb
class PuppetVersion < ApplicationRecord
  has_many :debuggers

  validates_presence_of :version
  validates_uniqueness_of :version
end

app/controllers/puppet_versions_controller.rb
class PuppetVersionsController < ApplicationController
  before_action :set_puppet_version, only: [:show, :edit, :update, :destroy]

  # GET /puppet_versions
  # GET /puppet_versions.json
  def index
    @puppet_versions = PuppetVersion.all
  end

  # GET /puppet_versions/1
  # GET /puppet_versions/1.json
  def show
  end

  # GET /puppet_versions/new
  def new
    @puppet_version = PuppetVersion.new
  end

  # GET /puppet_versions/1/edit
  def edit
  end

  # POST /puppet_versions
  # POST /puppet_versions.json
  def create
    @puppet_version = PuppetVersion.new(puppet_version_params)

    respond_to do |format|
      if @puppet_version.save
        format.html { redirect_to @puppet_version, notice: 'Puppet version was successfully created.' }
        format.json { render :show, status: :created, location: @puppet_version }
      else
        format.html { render :new }
        format.json { render json: @puppet_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puppet_versions/1
  # PATCH/PUT /puppet_versions/1.json
  def update
    respond_to do |format|
      if @puppet_version.update(puppet_version_params)
        format.html { redirect_to @puppet_version, notice: 'Puppet version was successfully updated.' }
        format.json { render :show, status: :ok, location: @puppet_version }
      else
        format.html { render :edit }
        format.json { render json: @puppet_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppet_versions/1
  # DELETE /puppet_versions/1.json
  def destroy
    @puppet_version.destroy
    respond_to do |format|
      format.html { redirect_to puppet_versions_url, notice: 'Puppet version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puppet_version
      @puppet_version = PuppetVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puppet_version_params
      params.require(:puppet_version).permit(:version)
    end
end

app/helpers/puppet_versions_helper.rb
module PuppetVersionsHelper
end

app/views/puppet_versions/_form.html.haml
= simple_form_for(@puppet_version) do |f|
  = f.error_notification

  .form-inputs
    = f.input :version

  .form-actions
    = f.button :submit

app/views/puppet_versions/edit.html.haml
%h1 Editing puppet_version

= render 'form'

= link_to 'Show', @puppet_version
\|
= link_to 'Back', puppet_versions_path

app/views/puppet_versions/index.html.haml
%h1 Listing puppet_versions

%table
  %thead
    %tr
      %th Version
      %th
      %th
      %th

  %tbody
    - @puppet_versions.each do |puppet_version|
      %tr
        %td= puppet_version.version
        %td= link_to 'Show', puppet_version
        %td= link_to 'Edit', edit_puppet_version_path(puppet_version)
        %td= link_to 'Destroy', puppet_version, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Puppet version', new_puppet_version_path

app/views/puppet_versions/new.html.haml
%h1 New puppet_version

= render 'form'

= link_to 'Back', puppet_versions_path

app/views/puppet_versions/show.html.haml
%p#notice= notice

%p
  %b Version:
  = @puppet_version.version

= link_to 'Edit', edit_puppet_version_path(@puppet_version)
\|
= link_to 'Back', puppet_versions_path