config/routes.rb
Rails.application.routes.draw do
  resources :puppet_modules
  resources :debuggers
  resources :puppet_versions
  resources :ruby_versions
  devise_for :users
  root to: "dashboard#index"
  resources :profiles

  resources :user_debugger_assignments, only: [:create, :destroy]
end

app/models/ruby_version.rb
class RubyVersion < ApplicationRecord
  has_many :debuggers
  validates_presence_of :version
  validates_uniqueness_of :version
end

app/controllers/ruby_versions_controller.rb
class RubyVersionsController < ApplicationController
  before_action :set_ruby_version, only: [:show, :edit, :update, :destroy]

  # GET /ruby_versions
  # GET /ruby_versions.json
  def index
    @ruby_versions = RubyVersion.all
  end

  # GET /ruby_versions/1
  # GET /ruby_versions/1.json
  def show
  end

  # GET /ruby_versions/new
  def new
    @ruby_version = RubyVersion.new
  end

  # GET /ruby_versions/1/edit
  def edit
  end

  # POST /ruby_versions
  # POST /ruby_versions.json
  def create
    @ruby_version = RubyVersion.new(ruby_version_params)

    respond_to do |format|
      if @ruby_version.save
        format.html { redirect_to @ruby_version, notice: 'Ruby version was successfully created.' }
        format.json { render :show, status: :created, location: @ruby_version }
      else
        format.html { render :new }
        format.json { render json: @ruby_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruby_versions/1
  # PATCH/PUT /ruby_versions/1.json
  def update
    respond_to do |format|
      if @ruby_version.update(ruby_version_params)
        format.html { redirect_to @ruby_version, notice: 'Ruby version was successfully updated.' }
        format.json { render :show, status: :ok, location: @ruby_version }
      else
        format.html { render :edit }
        format.json { render json: @ruby_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruby_versions/1
  # DELETE /ruby_versions/1.json
  def destroy
    @ruby_version.destroy
    respond_to do |format|
      format.html { redirect_to ruby_versions_url, notice: 'Ruby version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruby_version
      @ruby_version = RubyVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ruby_version_params
      params.require(:ruby_version).permit(:version)
    end
end

app/helpers/ruby_versions_helper.rb
module RubyVersionsHelper
end

app/views/ruby_versions/_form.html.haml
= simple_form_for(@ruby_version) do |f|
  = f.error_notification

  .form-inputs
    = f.input :version

  .form-actions
    = f.button :submit

app/views/ruby_versions/edit.html.haml
%h1 Editing ruby_version

= render 'form'

= link_to 'Show', @ruby_version
\|
= link_to 'Back', ruby_versions_path

app/views/ruby_versions/index.html.haml
%h1 Listing ruby_versions

%table
  %thead
    %tr
      %th Version
      %th
      %th
      %th

  %tbody
    - @ruby_versions.each do |ruby_version|
      %tr
        %td= ruby_version.version
        %td= link_to 'Show', ruby_version
        %td= link_to 'Edit', edit_ruby_version_path(ruby_version)
        %td= link_to 'Destroy', ruby_version, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ruby version', new_ruby_version_path

app/views/ruby_versions/new.html.haml
%h1 New ruby_version

= render 'form'

= link_to 'Back', ruby_versions_path

app/views/ruby_versions/show.html.haml
%p#notice= notice

%p
  %b Version:
  = @ruby_version.version

= link_to 'Edit', edit_ruby_version_path(@ruby_version)
\|
= link_to 'Back', ruby_versions_path