config/routes.rb
Rails.application.routes.draw do
  resources :puppet_modules
  resources :debuggers
  resources :puppet_versions
  resources :ruby_versions
  devise_for :users
  root to: "dashboard#index"
  resources :profiles

  resources :user_debugger_assignments, only: [:create, :destroy]
end

app/models/puppet_module.rb
class PuppetModule < ApplicationRecord

  has_many :puppet_module_debugger_assignments, dependent: :delete_all
  has_many :debuggers, through: :puppet_module_debugger_assignments

  validates_presence_of :name, :slug, :uri
  validates_uniqueness_of :name, :slug, :uri

end

app/controllers/puppet_modules_controller.rb
class PuppetModulesController < ApplicationController
  before_action :set_puppet_module, only: [:show, :edit, :update, :destroy]

  # GET /puppet_modules
  # GET /puppet_modules.json
  def index
    @puppet_modules = PuppetModule.all.order(:downloads)
  end

  # GET /puppet_modules/1
  # GET /puppet_modules/1.json
  def show
  end

  # GET /puppet_modules/new
  def new
    @puppet_module = PuppetModule.new
  end

  # GET /puppet_modules/1/edit
  def edit
  end

  # POST /puppet_modules
  # POST /puppet_modules.json
  def create
    @puppet_module = PuppetModule.new(puppet_module_params)

    respond_to do |format|
      if @puppet_module.save
        format.html { redirect_to @puppet_module, notice: 'Puppet module was successfully created.' }
        format.json { render :show, status: :created, location: @puppet_module }
      else
        format.html { render :new }
        format.json { render json: @puppet_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puppet_modules/1
  # PATCH/PUT /puppet_modules/1.json
  def update
    respond_to do |format|
      if @puppet_module.update(puppet_module_params)
        format.html { redirect_to @puppet_module, notice: 'Puppet module was successfully updated.' }
        format.json { render :show, status: :ok, location: @puppet_module }
      else
        format.html { render :edit }
        format.json { render json: @puppet_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppet_modules/1
  # DELETE /puppet_modules/1.json
  def destroy
    @puppet_module.destroy
    respond_to do |format|
      format.html { redirect_to puppet_modules_url, notice: 'Puppet module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puppet_module
      @puppet_module = PuppetModule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puppet_module_params
      params.require(:puppet_module).permit(:name, :version, :version_release_date, :owner, :slug, :uri)
    end
end

app/helpers/puppet_modules_helper.rb
module PuppetModulesHelper
end

app/views/puppet_modules/_form.html.haml
= simple_form_for(@puppet_module) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :slug
    = f.input :uri
    = f.input :downloads
    = f.input :supported
    = f.input :homepage_url
    = f.input :owner
    = f.input :current_release_version
    = f.input :release_supported

  .form-actions
    = f.button :submit

app/views/puppet_modules/edit.html.haml
%h1 Editing puppet_module

= render 'form'

= link_to 'Show', @puppet_module
\|
= link_to 'Back', puppet_modules_path

app/views/puppet_modules/index.html.haml
.container-fluid
  .row
    .col-xs-12
      %h1 Puppet Modules
      = link_to 'New Puppet module', new_puppet_module_path, class: 'btn btn-primary'

      %table.table.table-striped.table-sm
        %thead.thead-inverse
          %tr
            %th Name
            %th Slug
            %th URI
            %th Downloads
            %th Supported
            %th Homepage URL
            %th Owner
            %th Current Release Version
            %th Release Supported?
            %th
            %th
            %th

        %tbody
          - @puppet_modules.each do |puppet_module|
            %tr
              %td= puppet_module.name
              %td= puppet_module.slug
              %td= puppet_module.uri
              %td= puppet_module.downloads
              %td= puppet_module.supported
              %td= puppet_module.homepage_url
              %td= puppet_module.owner
              %td= puppet_module.current_release_version
              %td= puppet_module.release_supported
              %td= link_to 'Show', puppet_module
              %td= link_to 'Edit', edit_puppet_module_path(puppet_module)
              %td= link_to 'Destroy', puppet_module, :method => :delete, :data => { :confirm => 'Are you sure?' }

      %br

      = link_to 'New Puppet module', new_puppet_module_path, class: 'btn btn-primary'

app/views/puppet_modules/new.html.haml
%h1 New puppet_module

= render 'form'

= link_to 'Back', puppet_modules_path

app/views/puppet_modules/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @puppet_module.name
%p
  %b Version:
  = @puppet_module.version
%p
  %b Version release date:
  = @puppet_module.version_release_date
%p
  %b Owner:
  = @puppet_module.owner
%p
  %b Slug:
  = @puppet_module.slug
%p
  %b Uri:
  = @puppet_module.uri

= link_to 'Edit', edit_puppet_module_path(@puppet_module)
\|
= link_to 'Back', puppet_modules_path