config/routes.rb
Rails.application.routes.draw do
  resources :puppet_modules
  resources :debuggers
  resources :puppet_versions
  resources :ruby_versions
  devise_for :users
  root to: "dashboard#index"
  resources :profiles

  resources :user_debugger_assignments, only: [:create, :destroy]
end

app/models/debugger.rb
class Debugger < ApplicationRecord
  belongs_to :ruby_version
  belongs_to :puppet_version

  has_many :user_debugger_assignments, dependent: :delete_all
  has_many :users, through: :user_debugger_assignments

  has_many :puppet_module_debugger_assignments, dependent: :delete_all
  has_many :puppet_modules, through: :puppet_module_debugger_assignments

  accepts_nested_attributes_for :puppet_module_debugger_assignments
  accepts_nested_attributes_for :user_debugger_assignments
  accepts_nested_attributes_for :puppet_modules
  accepts_nested_attributes_for :users

  validates_presence_of :name, :ruby_version, :puppet_version
  validates_uniqueness_of :name

end

app/controllers/debuggers_controller.rb
class DebuggersController < ApplicationController
  before_action :set_debugger, only: [:show, :edit, :update, :destroy]

  # GET /debuggers
  # GET /debuggers.json
  def index
    @debuggers = Debugger.all
  end

  # GET /debuggers/1
  # GET /debuggers/1.json
  def show
  end

  # GET /debuggers/new
  def new
    @debugger = Debugger.new
    # @debugger.user_debugger_assignments.build.build_user
    # @debugger.puppet_module_debugger_assignments.build.build_puppet_module
  end

  # GET /debuggers/1/edit
  def edit
  end

  # POST /debuggers
  # POST /debuggers.json
  def create
    @debugger = Debugger.new(debugger_params)
    @debugger.save
    puppet_module_ids = params[:debugger][:puppet_module_ids]

    
    @debugger.users << User.find(params[:debugger][:user_id])

    params[:debugger][:puppet_module_ids].each do |pm_id|
      @debugger.puppet_modules << PuppetModule.find(pm_id) unless pm_id.blank?
    end


    # raise debugger_params[:puppet_module_ids].inspect


    # raise debugger_params.inspect
    # puppet_module_ids.each do |pm|
    #   @debugger.puppet_modules << PuppetModule.find(pm) unless pm.blank?
    # end

    respond_to do |format|
      if @debugger.save
        format.html { redirect_to @debugger, notice: 'Debugger was successfully created.' }
        format.json { render :show, status: :created, location: @debugger }
      else
        format.html { render :new }
        format.json { render json: @debugger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debuggers/1
  # PATCH/PUT /debuggers/1.json
  def update
    respond_to do |format|
      if @debugger.update(debugger_params)
        format.html { redirect_to @debugger, notice: 'Debugger was successfully updated.' }
        format.json { render :show, status: :ok, location: @debugger }
      else
        format.html { render :edit }
        format.json { render json: @debugger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debuggers/1
  # DELETE /debuggers/1.json
  def destroy
    @debugger.destroy
    respond_to do |format|
      format.html { redirect_to debuggers_url, notice: 'Debugger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debugger
      @debugger = Debugger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debugger_params
      # params.require(:debugger).permit(:name, :description, :ruby_version_id, :puppet_version_id,  :user_ids => [] )
      params.require(:debugger).permit(:name, :description, :ruby_version_id, :puppet_version_id,  :user_debugger_assignments => [ :user_id, :debugger_id],  :puppet_module_debugger_assignments => [ :puppet_module_id, :debugger_id] )
    end
    # def permitted_params
    #   params.permit(:work => [ :name, :description, :image_id, :standard_ids => [], :area_work_room_assignments_attributes => [ :room_id, :area_id ]])
    # end
end

app/helpers/debuggers_helper.rb
module DebuggersHelper
end

app/views/debuggers/_form.html.haml
= simple_form_for(@debugger) do |f|
  = f.error_notification

  - if @debugger.errors.full_messages.any?
    - @debugger.errors.full_messages.each do |error_message|
      = error_message if @debugger.errors.full_messages.first == error_message


  .form-inputs
    = f.input :name
    = f.input :description
    = f.association :ruby_version, label_method: :version
    = f.association :puppet_version, label_method: :version
    = f.association :puppet_modules, label_method: :name
    = f.hidden_field :user_id, value: current_user.id

  .form-actions
    = f.button :submit

app/views/debuggers/edit.html.haml
%h1 Editing debugger

= render 'form'

= link_to 'Show', @debugger
\|
= link_to 'Back', debuggers_path

app/views/debuggers/index.html.haml
.container-fluid
  .row
    .col-xs-12
      %h1.text-center.my-3
        Debuggers
  .row
    - @debuggers.each do |debugger|
      .col-xs-12.col-sm-6.col-md-4.mb-3
        .card
          %div{ :id => "#{debugger.id}"}
            .card-header
              %h4.card-title= debugger.name
            %img.card-img-top.img-fluid{:src => "http://placehold.it/600x200"}/
            .card-block
              %h6.card-subtitle.text-muted
                Ruby:
                = debugger.ruby_version.version
              %br
              %h6.card-subtitle.text-muted
                Puppet:
                = debugger.puppet_version.version
              %br
              %h6.card-subtitle.text-muted
                Puppet Modules:
                -pms = []
                - debugger.puppet_modules.each do |pm|
                  - pms << pm.name
                = pms.join(", ")
            .card-block
              / = link_to 'Add to Profile', user_debugger_assignments_path(debugger), class: 'btn btn-primary', method: :post
              %a.btn.btn-primary{:href => "#"} View Details
              %a.btn.btn-primary{:href => "#"} Use This

app/views/debuggers/new.html.haml
%h1 New debugger

= render 'form'

= link_to 'Back', debuggers_path

app/views/debuggers/show.html.haml
%p#notice= notice

.container-fluid
  .row
    .col-xs-12
      %h1.text-center.my-3
        Show Debugger
  .row
    .col-xs-12.col-sm-6.col-md-4
      .demo-card
        %div{ :id => "#{@debugger.id}"}
          .card-header
            %h4.card-title= @debugger.name
            = @debugger.description
          %img.card-img-top.img-fluid{:src => "http://placehold.it/600x200"}/
          .card-block
            %h6.card-subtitle.text-muted
              Ruby:
              = @debugger.ruby_version.version
            %br
            %h6.card-subtitle.text-muted
              Puppet:
              = @debugger.puppet_version.version
            %br
            %h6.card-subtitle.text-muted Puppet Modules:
            %ul.list-group.list-group-flush
              - @debugger.puppet_modules.each do |pm|
                %li.list-group-item= pm.name
          .card-block
            %a.btn.btn-primary{:href => "#"} Grab This
            %a.btn.btn-primary{:href => "#"} Details
            / %a.card-link{:href => "#"} Details
          .card-footer.text-muted
            This is a card footer


= link_to 'Edit', edit_debugger_path(@debugger)
\|
= link_to 'Back', debuggers_path